from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class SSQSection:
    key: str
    label_en: str
    label_zh: str
    weight: int
    step: int


SECTION_DEFINITIONS = [
    SSQSection("company_details", "Company Details", "公司信息", 0, 1),
    SSQSection("product_system", "Product / Construction System", "产品/建造体系", 0, 2),
    SSQSection("standards_certifications", "Standards & Certifications", "标准与认证", 20, 3),
    SSQSection("structural_steel_quality", "Structural Steel / LGS Quality", "结构钢/LGS质量", 18, 4),
    SSQSection("fire_resistance", "Fire Resistance", "防火性能", 14, 5),
    SSQSection("thermal_insulation", "Thermal Insulation", "保温隔热", 10, 6),
    SSQSection("acoustic_insulation", "Acoustic Insulation", "隔音性能", 6, 7),
    SSQSection("moisture_weather", "Moisture, Water, Mold & Weather Resistance", "防潮防水防霉与耐候性", 8, 8),
    SSQSection("assembly_transparency", "Full Wall/Roof/Floor Assembly", "完整墙体/屋面/地面构造", 10, 9),
    SSQSection("manufacturing_qa", "Manufacturing & Quality Control", "生产与质量管理", 6, 10),
    SSQSection("installation_support", "Installation & Engineering Support", "安装与工程支持", 3, 11),
    SSQSection("logistics_packaging", "Logistics & Packaging", "物流与包装", 2, 12),
    SSQSection("commercial_terms", "Commercial Terms", "商务条款", 2, 13),
    SSQSection("experience_references", "Experience & References", "经验与案例", 1, 14),
    SSQSection("final_declarations", "Final Declarations", "最终声明", 0, 15),
]


SECTION_WEIGHTS = {section.key: section.weight for section in SECTION_DEFINITIONS}

RISK_LEVELS = [
    (90, 100, "Excellent supplier"),
    (80, 89, "Strong supplier"),
    (70, 79, "Potential supplier - technical review required"),
    (60, 69, "High risk - proceed carefully"),
    (0, 59, "Not recommended"),
]

STATUS_CHOICES = [
    ("new", "New"),
    ("under_review", "Under Review"),
    ("approved", "Approved"),
    ("rejected", "Rejected"),
    ("need_more_info", "Need More Info"),
]

TOOLTIP_TERMS = {
    "r_value": {
        "en": "R-value: thermal resistance of a material/system. Higher is better insulation.",
        "zh": "R值：材料或系统的热阻值，数值越高，保温性能越好。",
    },
    "stc": {
        "en": "STC: Sound Transmission Class. Higher values mean better airborne sound insulation.",
        "zh": "STC：隔声等级，数值越高，空气声隔绝能力越强。",
    },
    "fire_rating": {
        "en": "Fire rating: tested duration (minutes) a system resists fire.",
        "zh": "耐火等级：系统在标准测试下可耐火的时间（分钟）。",
    },
    "yield_strength": {
        "en": "Yield strength: stress level (MPa) where steel starts permanent deformation.",
        "zh": "屈服强度：钢材开始产生永久变形时的应力（MPa）。",
    },
    "galvanization": {
        "en": "Galvanization (e.g. Z200/Z275): zinc coating mass for corrosion protection.",
        "zh": "镀锌层（如 Z200/Z275）：用于防腐蚀的锌层质量等级。",
    },
    "lgs_cfs": {
        "en": "LGS/CFS: Light Gauge/Cold Formed Steel structural systems.",
        "zh": "LGS/CFS：轻钢/冷弯薄壁钢结构体系。",
    },
}


CRITICAL_RULES = [
    ("missing_full_wall_section", "No full wall section"),
    ("missing_fire_test_report", "No fire rating report"),
    ("missing_structural_steel_spec", "No structural steel specification"),
    ("missing_certificates_or_tests", "No certificates/test reports"),
    ("missing_material_specification", "No clear material specification"),
    ("refuses_third_party_inspection", "Refuses third-party inspection"),
    ("claims_without_data", 'Only says "high quality" without data'),
]


SCORING_FIELDS = {
    "standards_certifications": [
        "standards_compliance",
        "iso_9001",
        "iso_14001",
        "ce_certificates",
        "third_party_lab_reports",
        "cert_scope",
        "original_test_reports",
        "israeli_engineer_review",
        "israeli_standard_adaptation",
    ],
    "structural_steel_quality": [
        "steel_type",
        "steel_grade",
        "yield_strength_mpa",
        "profile_thickness_mm",
        "galvanization_level",
        "profile_width",
        "stud_spacing",
        "openings_reinforcement",
        "pre_punched_profiles",
        "service_hole_spec",
        "screw_type_diameter",
        "anti_corrosion_protection",
        "expected_design_life",
    ],
    "fire_resistance": [
        "wall_fire_rating_min",
        "roof_fire_rating_min",
        "floor_fire_rating_min",
        "assembly_tested",
        "fire_test_standard",
        "fire_resistance_boards",
        "board_layers_count",
        "non_combustible_materials",
        "toxic_smoke_tests",
    ],
    "thermal_insulation": [
        "wall_r_value",
        "roof_r_value",
        "floor_r_value",
        "u_value",
        "insulation_type",
        "insulation_thickness",
        "insulation_density",
        "thermal_bridge_prevention",
        "hot_climate_suitability",
        "external_insulation_support",
        "insulation_upgrade_support",
    ],
    "acoustic_insulation": [
        "wall_stc_rating",
        "floor_acoustic_rating",
        "roof_acoustic_performance",
        "acoustic_test_report_available",
        "internal_board_layers",
        "acoustic_insulation_type_density",
    ],
    "moisture_weather": [
        "exterior_board_weather_resistance",
        "mold_resistant_materials",
        "wet_room_suitability",
        "external_board_type",
        "internal_board_type",
        "board_moisture_behavior",
        "waterproof_membrane_included",
        "vapor_barrier_included",
        "condensation_prevention_method",
        "coastal_environment_suitability",
    ],
    "assembly_transparency": [
        "total_wall_thickness",
        "wall_weight_per_m2",
        "external_cladding_type",
        "internal_board_type_assembly",
        "insulation_type_assembly",
        "waterproof_layer",
        "vapor_barrier_assembly",
        "air_gap_layer",
        "finishing_options",
        "tile_stone_support",
        "max_cladding_weight_per_m2",
    ],
    "manufacturing_qa": [
        "factory_ownership",
        "factory_size",
        "monthly_production_capacity",
        "qa_process",
        "incoming_material_inspection",
        "in_process_inspection",
        "final_inspection",
        "third_party_inspection_available",
        "production_photos_videos",
        "packing_list_before_shipment",
        "component_labeling",
        "installation_manual_available",
        "spare_parts_list_available",
    ],
    "installation_support": [
        "installation_drawings",
        "installation_manual",
        "online_training",
        "site_supervisor",
        "local_team_install_after_training",
        "install_time_100_120sqm",
        "workers_required",
        "required_tools_equipment",
        "foundation_requirements",
        "mep_coordination_support",
        "future_extension_support",
    ],
    "logistics_packaging": [
        "production_lead_time",
        "shipping_port_china",
        "packing_method",
        "shipping_anti_rust_protection",
        "shipping_moisture_protection",
        "sqm_per_40hq",
        "packing_optimization_per_project",
        "sequence_based_packing",
        "full_packing_list",
        "hs_codes_provided",
        "invoice_origin_certificate",
    ],
    "commercial_terms": [
        "price_per_sqm",
        "price_includes",
        "price_excludes",
        "moq",
        "payment_terms",
        "warranty_period",
        "warranty_coverage",
        "incoterms",
        "quotation_validity",
        "installation_cost_separate",
        "spare_parts_cost",
        "sample_cost",
        "engineering_design_cost",
        "mold_tooling_cost",
        "exclusive_distribution_support",
    ],
    "experience_references": [
        "completed_projects_count",
        "exported_countries",
        "residential_references",
        "hotel_public_references",
        "real_project_photos",
        "completed_project_videos",
        "customer_references",
        "middle_east_hot_climate_projects",
        "past_failures_and_resolution",
    ],
}


MANDATORY_FILE_FIELDS = {
    "certificates_uploads",
    "steel_certificate_upload",
    "structural_calculation_example_upload",
    "fire_test_reports_upload",
    "thermal_report_upload",
    "acoustic_report_upload",
    "water_moisture_report_upload",
    "wall_section_upload",
}


QUESTION_LABELS = {
    "company_name": {"en": "Company name", "zh": "公司名称"},
    "country": {"en": "Country", "zh": "国家"},
    "city": {"en": "City", "zh": "城市"},
    "website": {"en": "Website", "zh": "网站"},
    "contact_person": {"en": "Contact person", "zh": "联系人"},
    "job_title": {"en": "Job title", "zh": "职位"},
    "email": {"en": "Email", "zh": "电子邮箱"},
    "phone_whatsapp": {"en": "Phone / WhatsApp", "zh": "电话 / WhatsApp"},
    "wechat_id": {"en": "WeChat ID", "zh": "微信号"},
    "years_in_business": {"en": "Years in business", "zh": "经营年限"},
    "employees_count": {"en": "Number of employees", "zh": "员工人数"},
    "factory_address": {"en": "Factory address", "zh": "工厂地址"},
    "company_type": {"en": "Company type", "zh": "公司类型"},
    "main_products": {"en": "Main products", "zh": "主要产品"},
    "annual_capacity": {"en": "Annual production capacity", "zh": "年产能"},
    "export_markets": {"en": "Export markets", "zh": "出口市场"},
    "main_supply_countries": {"en": "Main countries currently supplied", "zh": "当前主要供应国家"},
    "israel_middle_east_experience": {"en": "Experience exporting to Israel or Middle East?", "zh": "是否有出口至以色列或中东经验？"},
    "product_type": {"en": "Product type", "zh": "产品类型"},
    "complete_system_or_components": {"en": "Complete system or components only?", "zh": "完整系统还是仅部件？"},
    "architectural_drawings": {"en": "Full architectural drawings?", "zh": "可提供完整建筑图纸？"},
    "structural_drawings": {"en": "Structural drawings?", "zh": "可提供结构图纸？"},
    "shop_drawings": {"en": "Shop drawings?", "zh": "可提供加工图？"},
    "adapt_israeli_requirements": {"en": "Adaptation to Israeli engineer requirements?", "zh": "可适配以色列工程师要求？"},
    "building_size_range": {"en": "Typical building size range", "zh": "典型建筑尺寸范围"},
    "floors_supported": {"en": "Number of floors supported", "zh": "支持楼层数"},
    "permanent_residential_use": {"en": "Suitable for permanent residential use?", "zh": "适用于永久住宅用途？"},
    "hot_climate_50": {"en": "Suitable for 45-50C hot climate?", "zh": "适用于45-50摄氏度高温气候？"},
    "coastal_suitability": {"en": "Suitable for coastal humidity/corrosion?", "zh": "适用于沿海高湿/腐蚀环境？"},
    "standards_compliance": {"en": "International standards", "zh": "符合的国际标准"},
    "iso_9001": {"en": "ISO 9001", "zh": "ISO 9001"},
    "iso_14001": {"en": "ISO 14001", "zh": "ISO 14001"},
    "ce_certificates": {"en": "CE certificates", "zh": "CE 证书"},
    "third_party_lab_reports": {"en": "Third-party lab test reports", "zh": "第三方实验室测试报告"},
    "cert_scope": {"en": "Certificates scope", "zh": "证书适用范围"},
    "original_test_reports": {"en": "Original test reports", "zh": "原始测试报告"},
    "israeli_engineer_review": {"en": "Israeli engineer review", "zh": "可供以色列工程师审查"},
    "israeli_standard_adaptation": {"en": "Adaptable to Israeli standards", "zh": "可适配以色列标准"},
    "steel_type": {"en": "Steel type", "zh": "钢材类型"},
    "steel_grade": {"en": "Steel grade", "zh": "钢材等级"},
    "yield_strength_mpa": {"en": "Yield strength (MPa)", "zh": "屈服强度 (MPa)"},
    "profile_thickness_mm": {"en": "Profile thickness (mm)", "zh": "型材厚度 (mm)"},
    "galvanization_level": {"en": "Galvanization level", "zh": "镀锌等级"},
    "profile_width": {"en": "Profile width", "zh": "型材宽度"},
    "stud_spacing": {"en": "Stud spacing", "zh": "立柱间距"},
    "openings_reinforcement": {"en": "Openings reinforcement", "zh": "门窗开口加固方式"},
    "pre_punched_profiles": {"en": "Pre-punched profiles", "zh": "型材预冲孔"},
    "service_hole_spec": {"en": "Service hole size/spacing", "zh": "管线孔尺寸/间距"},
    "screw_type_diameter": {"en": "Screw type/diameter", "zh": "螺钉类型/直径"},
    "anti_corrosion_protection": {"en": "Anti-corrosion protection", "zh": "防腐保护"},
    "expected_design_life": {"en": "Expected design life", "zh": "预期设计寿命"},
    "wall_fire_rating_min": {"en": "Wall fire rating (minutes)", "zh": "墙体耐火等级（分钟）"},
    "roof_fire_rating_min": {"en": "Roof fire rating", "zh": "屋面耐火等级"},
    "floor_fire_rating_min": {"en": "Floor fire rating", "zh": "楼板耐火等级"},
    "assembly_tested": {"en": "Complete assembly tested", "zh": "完整构造是否经过测试"},
    "fire_test_standard": {"en": "Fire test standard", "zh": "防火测试标准"},
    "fire_resistance_boards": {"en": "Fire-resistant boards", "zh": "防火板材"},
    "board_layers_count": {"en": "Board layers count", "zh": "板材层数"},
    "non_combustible_materials": {"en": "Non-combustible materials", "zh": "是否不燃材料"},
    "toxic_smoke_tests": {"en": "Toxic smoke tests", "zh": "有毒烟雾测试"},
    "wall_r_value": {"en": "Wall R-value", "zh": "墙体R值"},
    "roof_r_value": {"en": "Roof R-value", "zh": "屋面R值"},
    "floor_r_value": {"en": "Floor R-value", "zh": "楼板R值"},
    "u_value": {"en": "U-value", "zh": "U值"},
    "insulation_type": {"en": "Insulation type", "zh": "保温材料类型"},
    "insulation_thickness": {"en": "Insulation thickness", "zh": "保温厚度"},
    "insulation_density": {"en": "Insulation density", "zh": "保温密度"},
    "thermal_bridge_prevention": {"en": "Thermal bridge prevention", "zh": "热桥控制措施"},
    "hot_climate_suitability": {"en": "Hot climate suitability", "zh": "高温气候适配性"},
    "external_insulation_support": {"en": "External insulation support", "zh": "支持外保温层"},
    "insulation_upgrade_support": {"en": "Insulation upgrade support", "zh": "支持保温升级"},
    "wall_stc_rating": {"en": "Wall STC rating", "zh": "墙体STC等级"},
    "floor_acoustic_rating": {"en": "Floor acoustic rating", "zh": "楼板隔音等级"},
    "roof_acoustic_performance": {"en": "Roof acoustic performance", "zh": "屋面隔音性能"},
    "acoustic_test_report_available": {"en": "Acoustic test report available", "zh": "是否提供隔音测试报告"},
    "internal_board_layers": {"en": "Internal board layers", "zh": "内墙板层数"},
    "acoustic_insulation_type_density": {"en": "Insulation type and density", "zh": "隔音材料类型与密度"},
    "exterior_board_weather_resistance": {"en": "Exterior board weather resistance", "zh": "外墙板耐候性"},
    "mold_resistant_materials": {"en": "Mold-resistant materials", "zh": "防霉材料"},
    "wet_room_suitability": {"en": "Wet room suitability", "zh": "适用于潮湿空间"},
    "external_board_type": {"en": "External board type", "zh": "外层板材类型"},
    "internal_board_type": {"en": "Internal board type", "zh": "内层板材类型"},
    "board_moisture_behavior": {"en": "Board behavior under moisture", "zh": "受潮后板材表现"},
    "waterproof_membrane_included": {"en": "Waterproof membrane included", "zh": "是否包含防水膜"},
    "vapor_barrier_included": {"en": "Vapor barrier included", "zh": "是否包含隔汽层"},
    "condensation_prevention_method": {"en": "Condensation prevention method", "zh": "冷凝防治方法"},
    "coastal_environment_suitability": {"en": "Coastal environment suitability", "zh": "沿海环境适用性"},
    "total_wall_thickness": {"en": "Total wall thickness", "zh": "墙体总厚度"},
    "wall_weight_per_m2": {"en": "Wall weight per m2", "zh": "每平米墙体重量"},
    "external_cladding_type": {"en": "External cladding type", "zh": "外饰面类型"},
    "internal_board_type_assembly": {"en": "Internal board type (assembly)", "zh": "构造内层板材类型"},
    "insulation_type_assembly": {"en": "Insulation type (assembly)", "zh": "构造保温类型"},
    "waterproof_layer": {"en": "Waterproof layer", "zh": "防水层"},
    "vapor_barrier_assembly": {"en": "Vapor barrier (assembly)", "zh": "构造隔汽层"},
    "air_gap_layer": {"en": "Air gap / ventilation layer", "zh": "空气层/通风层"},
    "finishing_options": {"en": "Finishing options", "zh": "饰面选项"},
    "tile_stone_support": {"en": "Tile/stone cladding support", "zh": "可否安装瓷砖/石材"},
    "max_cladding_weight_per_m2": {"en": "Max cladding weight per m2", "zh": "最大饰面荷载（kg/m2）"},
    "factory_ownership": {"en": "Factory ownership", "zh": "工厂产权"},
    "factory_size": {"en": "Factory size", "zh": "工厂规模"},
    "monthly_production_capacity": {"en": "Monthly production capacity", "zh": "月产能"},
    "qa_process": {"en": "QA process", "zh": "质量管理流程"},
    "incoming_material_inspection": {"en": "Incoming material inspection", "zh": "来料检验"},
    "in_process_inspection": {"en": "In-process inspection", "zh": "过程检验"},
    "final_inspection": {"en": "Final inspection", "zh": "最终检验"},
    "third_party_inspection_available": {"en": "Third-party inspection available", "zh": "是否支持第三方验厂/检验"},
    "production_photos_videos": {"en": "Production photos/videos", "zh": "可提供生产照片/视频"},
    "packing_list_before_shipment": {"en": "Packing list before shipment", "zh": "出货前装箱清单"},
    "component_labeling": {"en": "Component labeling", "zh": "构件编号标识"},
    "installation_manual_available": {"en": "Installation manual available", "zh": "可提供安装手册"},
    "spare_parts_list_available": {"en": "Spare parts list available", "zh": "可提供备件清单"},
    "installation_drawings": {"en": "Installation drawings", "zh": "安装图纸"},
    "installation_manual": {"en": "Installation manual", "zh": "安装手册"},
    "online_training": {"en": "Online training", "zh": "在线培训"},
    "site_supervisor": {"en": "Site supervisor available", "zh": "可派现场指导"},
    "local_team_install_after_training": {"en": "Local team install after training", "zh": "培训后本地团队可安装"},
    "install_time_100_120sqm": {"en": "Install time for 100-120 sqm", "zh": "100-120平米安装周期"},
    "workers_required": {"en": "Workers required", "zh": "所需工人数"},
    "required_tools_equipment": {"en": "Required tools/equipment", "zh": "所需工具设备"},
    "foundation_requirements": {"en": "Foundation requirements", "zh": "基础要求"},
    "mep_coordination_support": {"en": "MEP coordination support", "zh": "机电协调支持"},
    "future_extension_support": {"en": "Future extension support", "zh": "后续扩建支持"},
    "production_lead_time": {"en": "Production lead time", "zh": "生产周期"},
    "shipping_port_china": {"en": "Shipping port in China", "zh": "中国装运港"},
    "packing_method": {"en": "Packing method", "zh": "包装方式"},
    "shipping_anti_rust_protection": {"en": "Anti-rust shipping protection", "zh": "运输防锈保护"},
    "shipping_moisture_protection": {"en": "Moisture shipping protection", "zh": "运输防潮保护"},
    "sqm_per_40hq": {"en": "sqm per 40HQ container", "zh": "每40HQ可装平方米数"},
    "packing_optimization_per_project": {"en": "Packing optimization by project", "zh": "按项目优化装箱"},
    "sequence_based_packing": {"en": "Packed by construction sequence", "zh": "按施工顺序包装"},
    "full_packing_list": {"en": "Full packing list provided", "zh": "提供完整装箱清单"},
    "hs_codes_provided": {"en": "HS codes provided", "zh": "提供HS编码"},
    "invoice_origin_certificate": {"en": "Invoice and certificate of origin", "zh": "商业发票与原产地证"},
    "price_per_sqm": {"en": "Price per sqm", "zh": "每平米价格"},
    "price_includes": {"en": "Price includes", "zh": "报价包含内容"},
    "price_excludes": {"en": "Price excludes", "zh": "报价不含内容"},
    "moq": {"en": "MOQ", "zh": "最小起订量"},
    "payment_terms": {"en": "Payment terms", "zh": "付款条款"},
    "warranty_period": {"en": "Warranty period", "zh": "质保期限"},
    "warranty_coverage": {"en": "Warranty coverage", "zh": "质保范围"},
    "incoterms": {"en": "Incoterms", "zh": "国际贸易术语"},
    "quotation_validity": {"en": "Quotation validity", "zh": "报价有效期"},
    "installation_cost_separate": {"en": "Installation cost separate", "zh": "安装费用是否单列"},
    "spare_parts_cost": {"en": "Spare parts cost", "zh": "备件费用"},
    "sample_cost": {"en": "Sample cost", "zh": "样品费用"},
    "engineering_design_cost": {"en": "Engineering/design cost", "zh": "工程/设计费用"},
    "mold_tooling_cost": {"en": "Mold/tooling cost", "zh": "模具/工装费用"},
    "exclusive_distribution_support": {"en": "Exclusive distribution support", "zh": "以色列独家代理支持"},
    "completed_projects_count": {"en": "Completed projects count", "zh": "已完成项目数量"},
    "exported_countries": {"en": "Exported countries", "zh": "出口国家"},
    "residential_references": {"en": "Residential references", "zh": "住宅项目案例"},
    "hotel_public_references": {"en": "Hotel/public references", "zh": "酒店/公建案例"},
    "customer_references": {"en": "Customer references", "zh": "客户参考信息"},
    "middle_east_hot_climate_projects": {"en": "Middle East/hot climate projects", "zh": "中东/高温气候项目"},
    "past_failures_and_resolution": {"en": "Past failures and resolution", "zh": "历史问题与解决措施"},
    "declaration_accuracy": {"en": "Declaration: answers are accurate", "zh": "声明：所填信息真实准确"},
    "declaration_missing_docs": {"en": "Declaration: missing docs may disqualify", "zh": "声明：缺失文件可能导致资格取消"},
    "declaration_engineer_review": {"en": "Declaration: reviewed by engineers", "zh": "声明：同意工程师审核资料"},
    "declaration_more_docs": {"en": "Declaration: can provide more documents", "zh": "声明：可按要求补充文件"},
}


CHOICE_VALUE_LABELS = {
    "company_type": {
        "manufacturer": {"en": "Manufacturer", "zh": "制造商"},
        "trading_company": {"en": "Trading company", "zh": "贸易公司"},
        "both": {"en": "Both", "zh": "两者皆有"},
    },
    "product_type": {
        "lgs_cfs": {"en": "LGS / CFS structure", "zh": "轻钢 / 冷弯薄壁钢结构"},
        "modular_house": {"en": "Modular house", "zh": "模块化房屋"},
        "container_house": {"en": "Container house", "zh": "集装箱房屋"},
        "hybrid_construction": {"en": "Hybrid construction", "zh": "混合建造体系"},
        "wall_panels": {"en": "Wall panels", "zh": "墙板系统"},
        "roofing_system": {"en": "Roofing system", "zh": "屋面系统"},
        "insulation_system": {"en": "Insulation system", "zh": "保温系统"},
        "other": {"en": "Other", "zh": "其他"},
    },
    "incoterms": {
        "EXW": {"en": "EXW", "zh": "EXW"},
        "FOB": {"en": "FOB", "zh": "FOB"},
        "CIF": {"en": "CIF", "zh": "CIF"},
        "DDP": {"en": "DDP", "zh": "DDP"},
    },
}

