# Generated by Django 6.0 on 2025-12-17 17:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient", models.EmailField(max_length=254, verbose_name="נמען")),
                ("subject", models.CharField(max_length=255, verbose_name="נושא")),
                (
                    "status",
                    models.CharField(
                        choices=[("SENT", "נשלח"), ("FAILED", "נכשל")],
                        max_length=20,
                        verbose_name="סטטוס",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="שגיאה (אם יש)"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="זמן שליחה"),
                ),
            ],
            options={
                "verbose_name": "יומן מייל",
                "verbose_name_plural": "יומן מיילים יוצאים",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="השאלה")),
                ("answer", models.TextField(verbose_name="התשובה")),
                (
                    "order",
                    models.IntegerField(
                        default=0, verbose_name="סדר הופעה (נמוך מופיע קודם)"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="להציג באתר?"),
                ),
            ],
            options={
                "verbose_name": "שאלה ותשובה",
                "verbose_name_plural": "שאלות ותשובות",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HouseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="שם הדגם")),
                ("description", models.TextField(verbose_name="תיאור כללי (ראשי)")),
                ("area_sqm", models.IntegerField(default=30, verbose_name='שטח במ"ר')),
                (
                    "min_rooms",
                    models.IntegerField(default=1, verbose_name="מספר חדרים (מ...)"),
                ),
                (
                    "max_rooms",
                    models.IntegerField(default=3, verbose_name="מספר חדרים (עד...)"),
                ),
                (
                    "specs",
                    models.TextField(blank=True, verbose_name="מפרט טכני ומידות"),
                ),
                (
                    "internal_layout",
                    models.TextField(blank=True, verbose_name="חלוקה פנימית"),
                ),
                (
                    "blueprint_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blueprints/",
                        verbose_name="תמונת שרטוט",
                    ),
                ),
                (
                    "price_estimate",
                    models.IntegerField(default=0, verbose_name="מחיר מחירון"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="שם השימוש")),
            ],
            options={
                "verbose_name": "סוג שימוש",
                "verbose_name_plural": "סוגי שימוש",
            },
        ),
        migrations.CreateModel(
            name="HouseMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="house_media/", verbose_name="קובץ"),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "תמונה"), ("video", "וידאו")],
                        default="image",
                        max_length=10,
                        verbose_name="סוג קובץ",
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="proposals.housemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="טלפון"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "favorites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favorited_by",
                        to="proposals.housemodel",
                        verbose_name="רשימת מועדפים",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HouseUpgrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="שם השדרוג")),
                ("price", models.IntegerField(verbose_name="מחיר תוספת")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="upgrades/",
                        verbose_name="תמונת השדרוג (אופציונלי)",
                    ),
                ),
                (
                    "is_included",
                    models.BooleanField(
                        default=False, verbose_name="מסומן כברירת מחדל?"
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upgrades",
                        to="proposals.housemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=100, verbose_name="שם הלקוח"),
                ),
                ("client_phone", models.CharField(max_length=20, verbose_name="טלפון")),
                (
                    "client_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="מייל לקבלת ההצעה"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=1, verbose_name="כמות יחידות"),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, verbose_name="הערות להצעה (יופיעו במייל)"
                    ),
                ),
                ("final_price", models.IntegerField(verbose_name='מחיר סופי (סה"כ)')),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "טיוטה/נשלח ללקוח"),
                            ("SIGNED", "הוזמן וחתום"),
                            ("DEPOSIT", "שולם מקדמה"),
                            ("PRODUCTION", "בייצור"),
                            ("SHIPPING", "במשלוח"),
                            ("COMPLETED", "הושלם"),
                            ("CANCELED", "בוטל"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="סטטוס הזמנה",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_signed", models.BooleanField(default=False)),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="signatures/",
                        verbose_name="קובץ חתימה",
                    ),
                ),
                (
                    "selected_house",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="proposals.housemodel",
                        verbose_name="בחר דגם",
                    ),
                ),
                (
                    "selected_upgrades",
                    models.ManyToManyField(
                        blank=True,
                        to="proposals.houseupgrade",
                        verbose_name="שדרוגים שנבחרו",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="housemodel",
            name="usage_types",
            field=models.ManyToManyField(
                blank=True, to="proposals.usagetype", verbose_name="סוגי שימוש מתאימים"
            ),
        ),
    ]
