# Generated by Django 6.0 on 2025-12-18 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emaillog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "יומן מייל (ישן)",
                "verbose_name_plural": "יומן מיילים (ישן)",
            },
        ),
        migrations.RemoveField(
            model_name="housemodel",
            name="max_rooms",
        ),
        migrations.RemoveField(
            model_name="housemodel",
            name="min_rooms",
        ),
        migrations.AlterField(
            model_name="faq",
            name="order",
            field=models.IntegerField(default=0, verbose_name="סדר הופעה"),
        ),
        migrations.CreateModel(
            name="ScheduledEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient", models.EmailField(max_length=254, verbose_name="נמען")),
                ("subject", models.CharField(max_length=255, verbose_name="נושא")),
                (
                    "pdf_content",
                    models.BinaryField(
                        blank=True, null=True, verbose_name="תוכן ה-PDF"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "ממתין לשליחה"),
                            ("SENT", "נשלח"),
                            ("FAILED", "נכשל"),
                            ("CANCELLED", "בוטל ידנית"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="סטטוס",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="שגיאה")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scheduled_for",
                    models.DateTimeField(verbose_name="זמן שליחה מתוכנן"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="נשלח בפועל ב"
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="proposals.quote",
                    ),
                ),
            ],
            options={
                "verbose_name": "מייל בתור (להשהייה)",
                "verbose_name_plural": "מיילים בתור / יוצאים",
                "ordering": ["scheduled_for"],
            },
        ),
    ]
