# Generated by Django 6.0 on 2025-12-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "proposals",
            "0002_alter_emaillog_options_remove_housemodel_max_rooms_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "טיוטה/נשלח ללקוח"),
                    ("INTERESTED", "לקוח מתעניין"),
                    ("SENT", "נשלח ללקוח"),
                    ("SIGNED", "הלקוח חתם"),
                    ("DEPOSIT", "שולם מקדמה"),
                    ("PRODUCTION", "בייצור"),
                    ("SHIPPING", "במשלוח"),
                    ("COMPLETED", "הושלם"),
                    ("CANCELED", "בוטל"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="סטטוס הזמנה",
            ),
        ),
    ]
