# Generated by Django 6.0 on 2025-12-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0003_quote_updated_at_alter_quote_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="deposit_percentage",
            field=models.IntegerField(default=30, verbose_name="אחוז מקדמה לתשלום"),
        ),
    ]
