# Generated by Django 6.0 on 2025-12-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0004_quote_deposit_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "טיוטה/נשלח ללקוח"),
                    ("INTERESTED", "לקוח מתעניין"),
                    ("SENT", "נשלח ללקוח"),
                    ("SIGNED", "הוזמן וחתום"),
                    ("DEPOSIT", "שולם מקדמה"),
                    ("PRODUCTION", "בייצור"),
                    ("SHIPPING", "במשלוח"),
                    ("COMPLETED", "הושלם"),
                    ("CANCELED", "בוטל"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="סטטוס הזמנה",
            ),
        ),
    ]
