# Generated by Django 6.0 on 2025-12-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0005_alter_quote_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="has_callback_request",
            field=models.BooleanField(
                default=False, verbose_name="🔥 ממתין לשיחת נציג"
            ),
        ),
    ]
