# Generated by Django 6.0 on 2025-12-20 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0006_quote_has_callback_request"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="client_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="שם הלקוח"),
        ),
        migrations.AlterField(
            model_name="quote",
            name="client_phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="טלפון"),
        ),
        migrations.AlterField(
            model_name="quote",
            name="final_price",
            field=models.IntegerField(default=0, verbose_name='מחיר סופי (סה"כ)'),
        ),
        migrations.AlterField(
            model_name="quote",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="לקוח רשום (אופציונלי)",
            ),
        ),
    ]
