# Generated by Django 6.0 on 2025-12-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0007_alter_quote_client_name_alter_quote_client_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="כתובת מגורים"
            ),
        ),
    ]
