# Generated by Django 5.1 on 2025-12-20 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0002_alter_clientprofile_id_alter_emaillog_id_and_more"),
        ("proposals", "0008_clientprofile_address"),
    ]

    operations = []
