# Generated by Django 5.1 on 2026-04-20 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0009_merge_20251220_1257"),
        ("proposals", "0014_add_light_mobile_house_type"),
    ]

    operations = []
