# Generated by Django 5.1 on 2026-04-20 17:07

from django.db import migrations, models


def backfill_housemedia_order_and_card(apps, schema_editor):
    HouseMedia = apps.get_model("proposals", "HouseMedia")
    HouseModel = apps.get_model("proposals", "HouseModel")
    for house in HouseModel.objects.all():
        media_list = list(HouseMedia.objects.filter(house=house).order_by("id"))
        first_image_done = False
        for i, m in enumerate(media_list):
            m.sort_order = i * 10
            if m.media_type == "image" and not first_image_done:
                m.is_homepage_card = True
                first_image_done = True
            else:
                m.is_homepage_card = False
            m.save(update_fields=["sort_order", "is_homepage_card"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0015_merge_20260420_1849"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="housemedia",
            options={
                "ordering": ["sort_order", "id"],
                "verbose_name": "מדיה לבית",
                "verbose_name_plural": "מדיה לבית",
            },
        ),
        migrations.AddField(
            model_name="housemedia",
            name="is_homepage_card",
            field=models.BooleanField(
                default=False,
                help_text="רק תמונה אחת לכל בית — זו שתופיע ברשימת הדגמים בדף הראשי.",
                verbose_name="תמונת כרטיס בדף הבית",
            ),
        ),
        migrations.AddField(
            model_name="housemedia",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="מספר נמוך יותר = מוצג ראשון בגלריה ובעמוד הבית.",
                verbose_name="סדר בתצוגה",
            ),
        ),
        migrations.RunPython(backfill_housemedia_order_and_card, noop_reverse),
    ]
