# Generated by Django 5.1 on 2026-04-21 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0016_housemedia_sort_homepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="TabHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=160, unique=True, verbose_name="Slug"),
                ),
                (
                    "model_name",
                    models.CharField(max_length=180, verbose_name="שם הדגם"),
                ),
                (
                    "subtitle_he",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="כותרת משנה"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("single-family", "בתים פרטיים"),
                            ("modular", "בתים מודולריים"),
                            ("adu", "ADU"),
                        ],
                        default="single-family",
                        max_length=30,
                        verbose_name="קטגוריה ראשית",
                    ),
                ),
                (
                    "bedrooms",
                    models.PositiveIntegerField(default=0, verbose_name="חדרי שינה"),
                ),
                (
                    "bathrooms",
                    models.PositiveIntegerField(default=0, verbose_name="חדרי רחצה"),
                ),
                (
                    "living_rooms",
                    models.PositiveIntegerField(default=1, verbose_name="סלונים"),
                ),
                (
                    "kitchen_count",
                    models.PositiveIntegerField(default=1, verbose_name="מטבחים"),
                ),
                (
                    "garages",
                    models.PositiveIntegerField(default=0, verbose_name="חניות"),
                ),
                (
                    "floors",
                    models.PositiveIntegerField(default=1, verbose_name="קומות"),
                ),
                ("area_m2", models.FloatField(default=0, verbose_name='שטח מ"ר')),
                (
                    "length_m",
                    models.FloatField(blank=True, null=True, verbose_name="אורך (מ')"),
                ),
                (
                    "width_m",
                    models.FloatField(blank=True, null=True, verbose_name="רוחב (מ')"),
                ),
                (
                    "description_he",
                    models.TextField(blank=True, verbose_name="תיאור מלא"),
                ),
                (
                    "features_he",
                    models.TextField(
                        blank=True,
                        help_text="כל שורה תוצג כיתרון נפרד בכרטיסים.",
                        verbose_name="פיצ'רים (שורה לכל פיצ'ר)",
                    ),
                ),
                (
                    "inquiry_cta_label",
                    models.CharField(
                        default="אני רוצה פרטים",
                        max_length=80,
                        verbose_name="טקסט כפתור פנייה",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="מפורסם ב-/tab"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="סדר תצוגה"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "house_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tab_houses",
                        to="proposals.housetype",
                        verbose_name="קטגוריות נוספות",
                    ),
                ),
            ],
            options={
                "verbose_name": "דגם /tab",
                "verbose_name_plural": "דגמי /tab",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TabHouseImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="tab_houses/", verbose_name="תמונה"),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("hero", "תמונה ראשית"),
                            ("gallery", "גלריה"),
                            ("floorplan", "שרטוט"),
                            ("lifestyle", "תמונת אווירה"),
                        ],
                        default="gallery",
                        max_length=20,
                        verbose_name="סוג תמונה",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="סדר"),
                ),
                (
                    "tab_house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="proposals.tabhouse",
                        verbose_name="דגם",
                    ),
                ),
            ],
            options={
                "verbose_name": "תמונת דגם /tab",
                "verbose_name_plural": "תמונות דגמי /tab",
                "ordering": ["image_type", "sort_order", "id"],
            },
        ),
    ]
