# Generated by Django 5.1 on 2026-05-01 05:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0017_tabhouse_tabhouseimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("companyName", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=100)),
                ("contactName", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("productType", models.CharField(blank=True, max_length=120)),
                ("answers", models.JSONField(blank=True, default=dict)),
                ("files", models.JSONField(blank=True, default=dict)),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "riskLevel",
                    models.CharField(default="Not recommended", max_length=120),
                ),
                ("scoreBreakdown", models.JSONField(blank=True, default=dict)),
                ("criticalFlags", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("need_more_info", "Need More Info"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("adminNotes", models.TextField(blank=True)),
                ("language", models.CharField(default="en", max_length=10)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Supplier Submission",
                "verbose_name_plural": "Supplier Submissions",
                "ordering": ["-createdAt"],
            },
        ),
    ]
