# Generated by Django 5.1 on 2026-05-30 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0019_housemodel_premium_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="housemodel",
            name="bathroom_value",
            field=models.CharField(
                blank=True,
                default="מותאם לדגם",
                max_length=120,
                verbose_name="ערך חדר רחצה בפס הפיצ'רים",
            ),
        ),
        migrations.AddField(
            model_name="housemodel",
            name="bedrooms_value",
            field=models.CharField(
                blank=True,
                default="מותאם לדגם",
                max_length=120,
                verbose_name="ערך חדרי שינה בפס הפיצ'רים",
            ),
        ),
        migrations.AddField(
            model_name="housemodel",
            name="built_area_value",
            field=models.CharField(
                blank=True,
                default="מותאם לדגם",
                max_length=120,
                verbose_name="ערך שטח בנוי בפס הפיצ'רים",
            ),
        ),
        migrations.AddField(
            model_name="housemodel",
            name="description_section_title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("תיאור הדגם", "תיאור הדגם"),
                    ("יתרונות הדגם", "יתרונות הדגם"),
                    ("מאפיינים עיקריים", "מאפיינים עיקריים"),
                    ("למה לבחור ב-APPLE?", "למה לבחור ב-APPLE?"),
                    ("מפרט ויתרונות", "מפרט ויתרונות"),
                    ("תכונות מרכזיות", "תכונות מרכזיות"),
                ],
                max_length=80,
                verbose_name="כותרת מקטע תיאור",
            ),
        ),
        migrations.AddField(
            model_name="housemodel",
            name="dimensions_text",
            field=models.TextField(blank=True, verbose_name="מידות"),
        ),
        migrations.AddField(
            model_name="housemodel",
            name="extra_images_section_title",
            field=models.CharField(
                blank=True,
                default="תמונות נוספות",
                max_length=80,
                verbose_name="כותרת מקטע תמונות נוספות",
            ),
        ),
        migrations.AddField(
            model_name="housemodel",
            name="highlights_section_title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("תיאור הדגם", "תיאור הדגם"),
                    ("יתרונות הדגם", "יתרונות הדגם"),
                    ("מאפיינים עיקריים", "מאפיינים עיקריים"),
                    ("למה לבחור ב-APPLE?", "למה לבחור ב-APPLE?"),
                    ("מפרט ויתרונות", "מפרט ויתרונות"),
                    ("תכונות מרכזיות", "תכונות מרכזיות"),
                ],
                max_length=80,
                verbose_name="כותרת מקטע יתרונות",
            ),
        ),
        migrations.AddField(
            model_name="housemodel",
            name="living_room_value",
            field=models.CharField(
                blank=True,
                default="כלול בדגם",
                max_length=120,
                verbose_name="ערך סלון מרווח בפס הפיצ'רים",
            ),
        ),
        migrations.AddField(
            model_name="housemodel",
            name="marketing_title",
            field=models.CharField(
                blank=True, max_length=180, verbose_name="כותרת שיווקית"
            ),
        ),
        migrations.AddField(
            model_name="housemodel",
            name="open_kitchen_value",
            field=models.CharField(
                blank=True,
                default="בהתאמה אישית",
                max_length=120,
                verbose_name="ערך מטבח פתוח בפס הפיצ'רים",
            ),
        ),
        migrations.AddField(
            model_name="housemodel",
            name="porch_value",
            field=models.CharField(
                blank=True,
                default="אופציונלי",
                max_length=120,
                verbose_name="ערך מרפסת בפס הפיצ'רים",
            ),
        ),
        migrations.AddField(
            model_name="housemodel",
            name="short_description_template",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "בחירה ידנית"),
                    (
                        "בית מודולרי יוקרתי בעיצוב מודרני וחדשני.",
                        "בית מודולרי יוקרתי בעיצוב מודרני וחדשני.",
                    ),
                    (
                        "פתרון מגורים חכם, מהיר ואיכותי.",
                        "פתרון מגורים חכם, מהיר ואיכותי.",
                    ),
                    (
                        "מבנה מתקדם המתאים למגורים, אירוח ועסקים.",
                        "מבנה מתקדם המתאים למגורים, אירוח ועסקים.",
                    ),
                    (
                        "שילוב מושלם של עיצוב, נוחות ועמידות.",
                        "שילוב מושלם של עיצוב, נוחות ועמידות.",
                    ),
                    (
                        "בית מוכן להצבה עם גימור ברמה גבוהה.",
                        "בית מוכן להצבה עם גימור ברמה גבוהה.",
                    ),
                ],
                max_length=255,
                verbose_name="תיאור קצר (מתוך רשימה)",
            ),
        ),
        migrations.AddField(
            model_name="housemodel",
            name="technical_section_title",
            field=models.CharField(
                blank=True,
                default="מפרט טכני",
                max_length=80,
                verbose_name="כותרת מקטע מפרט",
            ),
        ),
        migrations.CreateModel(
            name="HouseAdvantageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=255, verbose_name="יתרון / מאפיין"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="סדר תצוגה"),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advantage_items",
                        to="proposals.housemodel",
                        verbose_name="דגם",
                    ),
                ),
            ],
            options={
                "verbose_name": "יתרון / מאפיין",
                "verbose_name_plural": "יתרונות / מאפיינים",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HouseTechnicalSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=120, verbose_name="שם שדה")),
                ("value", models.CharField(max_length=255, verbose_name="ערך")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="סדר תצוגה"),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technical_specs",
                        to="proposals.housemodel",
                        verbose_name="דגם",
                    ),
                ),
            ],
            options={
                "verbose_name": "מפרט טכני",
                "verbose_name_plural": "מפרט טכני",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
