# Generated by Django 5.1 on 2026-05-30 17:37

from django.db import migrations, models


def seed_house_preset_rows(apps, schema_editor):
    HouseModel = apps.get_model("proposals", "HouseModel")
    HouseTechnicalSpec = apps.get_model("proposals", "HouseTechnicalSpec")
    HouseAdvantageItem = apps.get_model("proposals", "HouseAdvantageItem")

    technical_keys = [
        "structure_type",
        "built_area",
        "external_dimensions",
        "rooms_total",
        "bedrooms_total",
        "bathrooms_total",
        "living_room",
        "kitchen",
        "porch",
        "galvanized_steel_frame",
        "insulated_walls",
        "thermal_insulation",
        "acoustic_insulation",
        "aluminum_windows",
        "double_glazing",
        "entry_door",
        "interior_doors",
        "flooring",
        "exterior_cladding",
        "interior_cladding",
        "insulated_roof",
        "electrical_system",
        "plumbing_system",
        "ac_preparation",
        "equipped_bathroom",
        "equipped_kitchen",
        "water_sewage_preparation",
        "internet_preparation",
        "interior_lighting",
        "exterior_lighting",
        "full_furniture_option",
        "customization_option",
        "delivery_time",
        "installation_time",
        "transport_type",
        "need_crane",
        "need_foundation",
        "custom",
    ]
    advantage_keys = [
        "fast_construction",
        "ready_to_place",
        "modern_luxury_design",
        "high_quality_materials",
        "advanced_insulation",
        "low_maintenance",
        "fit_residential",
        "fit_guest_unit",
        "fit_office",
        "fit_clinic",
        "fit_adu",
        "fit_rental",
        "smart_space_usage",
        "large_windows",
        "luxury_look",
        "fast_installation",
        "upgrade_option",
        "layout_change_option",
        "weather_resistance",
        "cost_effective",
        "factory_controlled",
        "less_site_noise",
        "fit_private_and_hospitality",
        "easy_transport",
        "fit_multi_usage",
        "custom",
    ]

    for house in HouseModel.objects.all().iterator():
        for idx, key in enumerate(technical_keys):
            if not HouseTechnicalSpec.objects.filter(house=house, preset_key=key).exists():
                HouseTechnicalSpec.objects.create(
                    house=house,
                    preset_key=key,
                    is_enabled=False,
                    sort_order=idx,
                    value="",
                    label="",
                )
        for idx, key in enumerate(advantage_keys):
            if not HouseAdvantageItem.objects.filter(house=house, preset_key=key).exists():
                HouseAdvantageItem.objects.create(
                    house=house,
                    preset_key=key,
                    is_enabled=False,
                    sort_order=idx,
                    text="",
                )


class Migration(migrations.Migration):

    dependencies = [
        (
            "proposals",
            "0020_housemodel_bathroom_value_housemodel_bedrooms_value_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="houseadvantageitem",
            name="is_enabled",
            field=models.BooleanField(default=True, verbose_name="להציג באתר (V)"),
        ),
        migrations.AddField(
            model_name="houseadvantageitem",
            name="preset_key",
            field=models.CharField(
                choices=[
                    ("fast_construction", "בנייה מהירה"),
                    ("ready_to_place", "פתרון מגורים מוכן להצבה"),
                    ("modern_luxury_design", "עיצוב מודרני ויוקרתי"),
                    ("high_quality_materials", "איכות חומרים גבוהה"),
                    ("advanced_insulation", "בידוד מתקדם לחיסכון באנרגיה"),
                    ("low_maintenance", "תחזוקה נמוכה לאורך שנים"),
                    ("fit_residential", "מתאים למגורים"),
                    ("fit_guest_unit", "מתאים לצימר / יחידת אירוח"),
                    ("fit_office", "מתאים למשרד"),
                    ("fit_clinic", "מתאים לקליניקה"),
                    ("fit_adu", "מתאים ליחידת דיור משלימה"),
                    ("fit_rental", "מתאים להשכרה"),
                    ("smart_space_usage", "ניצול חכם של החלל"),
                    ("large_windows", "חלונות גדולים להכנסת אור טבעי"),
                    ("luxury_look", "מראה יוקרתי ומזמין"),
                    ("fast_installation", "התקנה מהירה באתר"),
                    ("upgrade_option", "אפשרות לשדרוגים"),
                    ("layout_change_option", "אפשרות לשינוי חלוקה פנימית"),
                    ("weather_resistance", "עמידות גבוהה בתנאי מזג אוויר"),
                    ("cost_effective", "פתרון חסכוני ביחס לבנייה רגילה"),
                    ("factory_controlled", "ייצור מבוקר במפעל"),
                    ("less_site_noise", "פחות לכלוך ורעש באתר"),
                    (
                        "fit_private_and_hospitality",
                        "מתאים לקרקע פרטית / משק / מתחם אירוח",
                    ),
                    ("easy_transport", "ניתן לשינוע והצבה מהירה"),
                    ("fit_multi_usage", "מתאים למגוון שימושים פרטיים ועסקיים"),
                    ("custom", "טקסט מותאם אישית"),
                ],
                default="custom",
                max_length=60,
                verbose_name="יתרון מובנה",
            ),
        ),
        migrations.AddField(
            model_name="housetechnicalspec",
            name="is_enabled",
            field=models.BooleanField(default=True, verbose_name="להציג באתר (V)"),
        ),
        migrations.AddField(
            model_name="housetechnicalspec",
            name="preset_key",
            field=models.CharField(
                choices=[
                    ("structure_type", "סוג המבנה"),
                    ("built_area", "שטח בנוי"),
                    ("external_dimensions", "מידות חיצוניות"),
                    ("rooms_total", "מספר חדרים"),
                    ("bedrooms_total", "מספר חדרי שינה"),
                    ("bathrooms_total", "מספר חדרי רחצה"),
                    ("living_room", "סלון"),
                    ("kitchen", "מטבח"),
                    ("porch", "מרפסת"),
                    ("galvanized_steel_frame", "שלד פלדה מגולוונת"),
                    ("insulated_walls", "קירות מבודדים"),
                    ("thermal_insulation", "בידוד תרמי"),
                    ("acoustic_insulation", "בידוד אקוסטי"),
                    ("aluminum_windows", "חלונות אלומיניום"),
                    ("double_glazing", "זכוכית כפולה"),
                    ("entry_door", "דלת כניסה"),
                    ("interior_doors", "דלתות פנים"),
                    ("flooring", "ריצוף"),
                    ("exterior_cladding", "חיפוי חוץ"),
                    ("interior_cladding", "חיפוי פנים"),
                    ("insulated_roof", "גג מבודד"),
                    ("electrical_system", "מערכת חשמל"),
                    ("plumbing_system", "מערכת אינסטלציה"),
                    ("ac_preparation", "הכנה למיזוג אוויר"),
                    ("equipped_bathroom", "חדר רחצה מאובזר"),
                    ("equipped_kitchen", "מטבח מאובזר"),
                    ("water_sewage_preparation", "הכנה למים וביוב"),
                    ("internet_preparation", "הכנה לאינטרנט / תקשורת"),
                    ("interior_lighting", "תאורת פנים"),
                    ("exterior_lighting", "תאורת חוץ"),
                    ("full_furniture_option", "אפשרות לריהוט מלא"),
                    ("customization_option", "אפשרות להתאמה אישית"),
                    ("delivery_time", "זמן אספקה"),
                    ("installation_time", "זמן התקנה"),
                    ("transport_type", "סוג הובלה"),
                    ("need_crane", "צורך במנוף"),
                    ("need_foundation", "צורך בהכנת תשתית / יסודות"),
                    ("custom", "טקסט מותאם אישית"),
                ],
                default="custom",
                max_length=60,
                verbose_name="פריט מובנה",
            ),
        ),
        migrations.AlterField(
            model_name="houseadvantageitem",
            name="text",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="טקסט מותאם (לפריט מותאם)"
            ),
        ),
        migrations.AlterField(
            model_name="housetechnicalspec",
            name="label",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="כותרת מותאמת (לפריט מותאם)"
            ),
        ),
        migrations.AlterField(
            model_name="housetechnicalspec",
            name="value",
            field=models.CharField(blank=True, max_length=255, verbose_name="ערך"),
        ),
        migrations.RunPython(seed_house_preset_rows, migrations.RunPython.noop),
    ]
