# Generated by Django 5.1 on 2026-05-30 17:53

from django.db import migrations, models


def disable_empty_enabled_rows(apps, schema_editor):
    HouseTechnicalSpec = apps.get_model("proposals", "HouseTechnicalSpec")
    HouseAdvantageItem = apps.get_model("proposals", "HouseAdvantageItem")

    for spec in HouseTechnicalSpec.objects.filter(is_enabled=True).iterator():
        value_text = str(spec.value or "").strip()
        if not value_text:
            spec.is_enabled = False
            spec.save(update_fields=["is_enabled"])

    for advantage in HouseAdvantageItem.objects.filter(is_enabled=True).iterator():
        preset_key = str(advantage.preset_key or "").strip()
        text_value = str(advantage.text or "").strip()
        if preset_key == "custom" and not text_value:
            advantage.is_enabled = False
            advantage.save(update_fields=["is_enabled"])


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0021_houseadvantageitem_is_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="houseadvantageitem",
            name="is_enabled",
            field=models.BooleanField(default=False, verbose_name="להציג באתר (V)"),
        ),
        migrations.AlterField(
            model_name="housetechnicalspec",
            name="is_enabled",
            field=models.BooleanField(default=False, verbose_name="להציג באתר (V)"),
        ),
        migrations.RunPython(disable_empty_enabled_rows, migrations.RunPython.noop),
    ]
