# Generated by Django 5.1 on 2026-05-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0022_alter_houseadvantageitem_is_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="housemodel",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="טלפון ליצירת קשר בדף הדגם"
            ),
        ),
        migrations.AddField(
            model_name="housemodel",
            name="hero_subtitle",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="כותרת משנה לאזור הפתיחה"
            ),
        ),
        migrations.AddField(
            model_name="housemodel",
            name="whatsapp_link",
            field=models.URLField(blank=True, verbose_name="קישור וואטסאפ בדף הדגם"),
        ),
        migrations.AlterField(
            model_name="housemedia",
            name="is_homepage_card",
            field=models.BooleanField(
                default=False,
                help_text="פריט אחד בלבד יכול להיות ראשי (תמונה או וידאו) עבור ה-Hero בדף הדגם.",
                verbose_name="מדיה ראשית לדף הדגם",
            ),
        ),
    ]
